Repository pscedu/singularity-blast, pull requests merged in 2021-06, with the labels that each got.

#3 Update LICENSE
  2.9.0/Singularity
  CONTRIBUTING.md
  LICENSE
  README.md
Labels: documentation, enhancement

#4 Update Singularity
  2.9.0/Singularity
Labels: documentation, enhancement

#6 Update main.yml
  .github/workflows/main.yml
Labels: bug

#5 Update README.md
  README.md
Labels: documentation
